APP_TITLE = "Task Proxy + Wallet"
APP_VERSION = "2.2.0"

# Upstream configuration
UPSTREAM_BASE_URL = "https://xgodo.com"
UPSTREAM_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NzdhMDIxOTQxY2VkY2RjOTg4NmE2MSIsInVzZXJuYW1lIjoiaXRhY2hpdWNoaWhhYTI4Y3h0ZyIsImlhdCI6MTc2OTQ0NzQ1NywiZXhwIjo0ODkzNjQ5ODU3fQ.RWovXNp8xAKl6ZbiM5hZf1JHV8MT1vUpTn09NN0lbbo"
UPSTREAM_JOB_ID = "69339726ce0295f74e58fe84"

# Credit settings
CREDIT_PER_CONFIRMED = 10

# Turso database configuration
DB_URL = "libsql://gg-anime.aws-ap-south-1.turso.io"
DB_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NzAzOTg1MTUsImlkIjoiN2Y1NTA0N2YtZmU5OC00NGVjLTliY2QtNmJjMDQ0ZDU1MTljIiwicmlkIjoiNjE5ZWNhNTktYjFlNi00YWQyLWIyMDQtYTVkNTUxNjU5Mjk1In0.Qcbf8BexSLdZAegoxlAFJcCwJLFn_mD2GDhgfL5gXhRMnrP3aTRl3IsI2SCGxWiN79FMWf3GbV2aPtdIJiBkCg"

# App/server settings
HOST = "0.0.0.0"
PORT = 8000
RELOAD = False

APP_SECRET = "gotit"
SESSION_COOKIE = "okay"

SQLITE_TIMEOUT_SECONDS = 30.0
SQLITE_BUSY_TIMEOUT_MS = 8000

# Recovery email "theme"
RECOVERY_DOMAIN = "xneko.xyz"
